services:
  - type: web
    name: metabase
    env: docker
    repo: https://github.com/lexpierce/metabase.git # optional
    plan: standard # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: metabase-db
          property: connectionString
databases:
  - name: metabase-db
    databaseName: metabasedb
    plan: basic-256mb
    diskSizeGB: 5
    ipAllowList: [] # only allow internal connections
